site_name: aggdisagg
theme:
  name: material
  palette:
    primary: indigo
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - API Reference: api.md
  - Examples: examples.md
  - Benchmarks: benchmarks.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
